name: Node.js application

on:
  - push

env:
  CI: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm ci
#      - name: Build application
#        run: npm run build
#      - name: Run db migrations
#        run: npm run db:migrate
#      - name: Run linters
#        run: npm run linter:js
      - name: Run tests
        run: npm run test
